# Generated by Django 3.2.6 on 2021-09-26 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auctionlistings_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('howmuch', models.FloatField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidd', to=settings.AUTH_USER_MODEL)),
                ('whichListing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offereds', to='auctions.auctionlistings')),
            ],
        ),
    ]
